// Trivia Trixie - Question Bank (200 questions across 21 kid-friendly topics)
// Format: { c: category, q: question text, o: [4 options], a: index of correct option }
var TT = TT || {};

TT.CATEGORIES = [
    "SpongeBob", "TMNT", "Zombies", "Descendants", "Simpsons",
    "Spirited Away", "Christmas", "Easter", "Grinch", "Dr. Seuss",
    "Cat in the Hat", "Elf", "Lollies", "Fairies", "Faraway Tree",
    "Ghostbusters", "Toys", "Toy Story", "Pixar", "Disney", "Pop Culture"
];

// Maps a category name to the base filename of its scene artwork (assets/scene_<key>.png)
TT.CATEGORY_SCENES = {
    "SpongeBob": "spongebob",
    "TMNT": "tmnt",
    "Zombies": "zombies",
    "Descendants": "descendants",
    "Simpsons": "simpsons",
    "Spirited Away": "spiritedaway",
    "Christmas": "christmas",
    "Easter": "easter",
    "Grinch": "grinch",
    "Dr. Seuss": "drseuss",
    "Cat in the Hat": "catinthehat",
    "Elf": "elf",
    "Lollies": "lollies",
    "Fairies": "fairies",
    "Faraway Tree": "farawaytree",
    "Ghostbusters": "ghostbusters",
    "Toys": "toys",
    "Toy Story": "toystory",
    "Pixar": "pixar",
    "Disney": "disney",
    "Pop Culture": "popculture"
};

TT.QUESTIONS = [
    // --- SpongeBob (13) ---
    { c: "SpongeBob", q: "Where does SpongeBob SquarePants live?", o: ["A pineapple under the sea", "A sandcastle on the beach", "A rock in the desert", "A treehouse in the jungle"], a: 0 },
    { c: "SpongeBob", q: "What is the name of SpongeBob's pet snail?", o: ["Gary", "Patrick", "Squidward", "Sandy"], a: 0 },
    { c: "SpongeBob", q: "What is SpongeBob's job at the Krusty Krab?", o: ["Cashier", "Fry cook", "Manager", "Dishwasher"], a: 1 },
    { c: "SpongeBob", q: "Who is SpongeBob's best friend, a pink starfish?", o: ["Patrick Star", "Squidward", "Plankton", "Larry"], a: 0 },
    { c: "SpongeBob", q: "Which grumpy octopus lives next door to SpongeBob?", o: ["Squidward Tentacles", "Mr. Krabs", "Plankton", "Patrick"], a: 0 },
    { c: "SpongeBob", q: "Who owns the Krusty Krab restaurant?", o: ["Mr. Krabs", "Plankton", "Squidward", "SpongeBob"], a: 0 },
    { c: "SpongeBob", q: "What is the name of the town where SpongeBob lives?", o: ["Bikini Bottom", "Coral City", "Shell Harbor", "Ocean View"], a: 0 },
    { c: "SpongeBob", q: "Who is the tiny evil villain who owns the Chum Bucket?", o: ["Plankton", "Squidward", "Mr. Krabs", "Patrick"], a: 0 },
    { c: "SpongeBob", q: "What does SpongeBob attend to learn how to drive a boat?", o: ["Boating School", "Cooking Class", "Swim Club", "Fry Cook Academy"], a: 0 },
    { c: "SpongeBob", q: "What kind of animal is Sandy Cheeks?", o: ["A squirrel", "A crab", "A dolphin", "A jellyfish"], a: 0 },
    { c: "SpongeBob", q: "What game do SpongeBob and Patrick love to play with special nets?", o: ["Jellyfishing", "Fishball", "Bubble Tag", "Krab Catch"], a: 0 },
    { c: "SpongeBob", q: "What shape are SpongeBob's pants?", o: ["Square", "Round", "Triangle", "Star-shaped"], a: 0 },
    { c: "SpongeBob", q: "What is the secret recipe that makes Krabby Patties so delicious?", o: ["The Krabby Patty formula", "Plankton's secret sauce", "Squidward's spice mix", "Sandy's peanut butter"], a: 0 },

    // --- TMNT (10) ---
    { c: "TMNT", q: "How many Teenage Mutant Ninja Turtles are there?", o: ["Four", "Three", "Five", "Six"], a: 0 },
    { c: "TMNT", q: "Who is the wise rat who trains the turtles in ninjutsu?", o: ["Splinter", "Shredder", "Casey Jones", "April"], a: 0 },
    { c: "TMNT", q: "Which turtle wears a red mask and fights with sais?", o: ["Raphael", "Leonardo", "Michelangelo", "Donatello"], a: 0 },
    { c: "TMNT", q: "Which turtle wears a blue mask and leads the team?", o: ["Leonardo", "Raphael", "Michelangelo", "Donatello"], a: 0 },
    { c: "TMNT", q: "Which turtle wears an orange mask and loves pizza and jokes?", o: ["Michelangelo", "Leonardo", "Raphael", "Donatello"], a: 0 },
    { c: "TMNT", q: "Which turtle wears a purple mask and is the team's inventor?", o: ["Donatello", "Michelangelo", "Raphael", "Leonardo"], a: 0 },
    { c: "TMNT", q: "What is the Ninja Turtles' favorite food?", o: ["Pizza", "Tacos", "Burgers", "Spaghetti"], a: 0 },
    { c: "TMNT", q: "Where do the Ninja Turtles make their home?", o: ["In the sewers of New York City", "On a farm", "In a treehouse", "On a spaceship"], a: 0 },
    { c: "TMNT", q: "What is the name of the turtles' human reporter friend?", o: ["April O'Neil", "Karai", "Irma", "Vernon"], a: 0 },
    { c: "TMNT", q: "Who is the masked villain leader who is the turtles' arch-enemy?", o: ["Shredder", "Bebop", "Rocksteady", "Krang"], a: 0 },

    // --- Zombies (Disney) (9) ---
    { c: "Zombies", q: "What kind of creature is Zed, the main character of ZOMBIES?", o: ["A zombie", "A werewolf", "A vampire", "A ghost"], a: 0 },
    { c: "Zombies", q: "What is the name of the high school in the movie ZOMBIES?", o: ["Seabrook High", "Zombietown High", "Central High", "Mighty Shrimp Academy"], a: 0 },
    { c: "Zombies", q: "What is the name of the cheerleader who becomes friends with Zed?", o: ["Addison", "Bree", "Eliza", "Bonzo"], a: 0 },
    { c: "Zombies", q: "Besides zombies and humans, what other group lives in Seabrook?", o: ["Werewolves", "Vampires", "Mermaids", "Fairies"], a: 0 },
    { c: "Zombies", q: "What sport does Zed dream of playing at his new school?", o: ["Football", "Basketball", "Soccer", "Baseball"], a: 0 },
    { c: "Zombies", q: "What color hair does Addison hide under a wig?", o: ["White", "Green", "Blue", "Purple"], a: 0 },
    { c: "Zombies", q: "What is the name of the town where ZOMBIES takes place?", o: ["Seabrook", "Bikini Bottom", "Whoville", "Auradon"], a: 0 },
    { c: "Zombies", q: "What do zombies wear on their wrists to control their zombie urges in ZOMBIES?", o: ["Z-Bands", "Ankle bracelets", "Glow rings", "Magic bracelets"], a: 0 },
    { c: "Zombies", q: "What kind of Disney movie is ZOMBIES, mixing monsters with music?", o: ["A musical", "A silent film", "A documentary", "A puppet show"], a: 0 },

    // --- Descendants (9) ---
    { c: "Descendants", q: "Who is the daughter of Maleficent in Descendants?", o: ["Mal", "Evie", "Uma", "Jane"], a: 0 },
    { c: "Descendants", q: "Where do the villain kids live before coming to Auradon?", o: ["The Isle of the Lost", "Neverland", "Whoville", "Wonderland"], a: 0 },
    { c: "Descendants", q: "What is the name of the kingdom where the Disney heroes live?", o: ["Auradon", "Arendelle", "Agrabah", "Auroraland"], a: 0 },
    { c: "Descendants", q: "Who is the daughter of the Evil Queen in Descendants?", o: ["Evie", "Mal", "Jane", "Uma"], a: 0 },
    { c: "Descendants", q: "Whose son is Carlos, who is afraid of dogs at first?", o: ["Cruella De Vil", "Jafar", "Ursula", "Gaston"], a: 0 },
    { c: "Descendants", q: "Whose son is Jay, a talented thief and athlete?", o: ["Jafar", "Cruella De Vil", "Hades", "Captain Hook"], a: 0 },
    { c: "Descendants", q: "Who is the prince that Mal falls in love with?", o: ["Ben", "Chad", "Doug", "Harry"], a: 0 },
    { c: "Descendants", q: "Whose daughter is Uma, the pirate captain?", o: ["Ursula", "Maleficent", "Cruella De Vil", "Jafar"], a: 0 },
    { c: "Descendants", q: "What magical item does Mal need to steal in the first Descendants movie?", o: ["The Fairy Godmother's wand", "A magic mirror", "A glass slipper", "A poisoned apple"], a: 0 },

    // --- Simpsons (12) ---
    { c: "Simpsons", q: "What is the name of the town where the Simpsons live?", o: ["Springfield", "Shelbyville", "Ogdenville", "Capital City"], a: 0 },
    { c: "Simpsons", q: "What does Bart Simpson love to ride around town?", o: ["A skateboard", "A bicycle", "A scooter", "A unicycle"], a: 0 },
    { c: "Simpsons", q: "What is Homer Simpson's favorite snack?", o: ["Donuts", "Cookies", "Pretzels", "Chips"], a: 0 },
    { c: "Simpsons", q: "What color is the Simpson family's skin in the cartoon?", o: ["Yellow", "Blue", "Green", "Pink"], a: 0 },
    { c: "Simpsons", q: "What is the name of the Simpsons' pet dog?", o: ["Santa's Little Helper", "Rex", "Buddy", "Scruffy"], a: 0 },
    { c: "Simpsons", q: "Who is the baby of the Simpson family?", o: ["Maggie", "Lisa", "Bart", "Patty"], a: 0 },
    { c: "Simpsons", q: "What instrument does Lisa Simpson love to play?", o: ["Saxophone", "Piano", "Guitar", "Drums"], a: 0 },
    { c: "Simpsons", q: "Where does Homer Simpson work?", o: ["The nuclear power plant", "A donut shop", "A school", "A hospital"], a: 0 },
    { c: "Simpsons", q: "Who is Bart's best friend with orange hair and glasses?", o: ["Milhouse", "Nelson", "Ralph", "Martin"], a: 0 },
    { c: "Simpsons", q: "What is the name of the Simpsons' cat?", o: ["Snowball", "Whiskers", "Tom", "Felix"], a: 0 },
    { c: "Simpsons", q: "What is Homer's job title at the power plant?", o: ["Safety inspector", "Engineer", "Manager", "Scientist"], a: 0 },
    { c: "Simpsons", q: "What clown does Bart love to watch on TV?", o: ["Krusty the Clown", "Bonzo", "Ronald", "Chuckles"], a: 0 },

    // --- Spirited Away (8) ---
    { c: "Spirited Away", q: "What is the name of the girl who is the main character of Spirited Away?", o: ["Chihiro", "Kiki", "Ponyo", "Mei"], a: 0 },
    { c: "Spirited Away", q: "What happens to Chihiro's parents after they eat mysterious food?", o: ["They turn into pigs", "They fall asleep", "They disappear", "They turn into statues"], a: 0 },
    { c: "Spirited Away", q: "What kind of building is the magical place Chihiro must work in?", o: ["A bathhouse for spirits", "A castle", "A train station", "A school"], a: 0 },
    { c: "Spirited Away", q: "Who runs the bathhouse and has a giant head and tiny body?", o: ["Yubaba", "Zeniba", "Haku", "No-Face"], a: 0 },
    { c: "Spirited Away", q: "What is the name of the boy who helps Chihiro and can turn into a dragon?", o: ["Haku", "Boh", "Kamaji", "Lin"], a: 0 },
    { c: "Spirited Away", q: "What must Chihiro remember in order to leave the spirit world?", o: ["Her true name", "A magic spell", "Her parents' names", "A secret password"], a: 0 },
    { c: "Spirited Away", q: "What are the little black, dust-like creatures that carry coal in the bathhouse?", o: ["Soot sprites", "Fireflies", "Ghosts", "Fairies"], a: 0 },
    { c: "Spirited Away", q: "What famous animation studio made Spirited Away?", o: ["Studio Ghibli", "Pixar", "Disney", "DreamWorks"], a: 0 },

    // --- Christmas (14) ---
    { c: "Christmas", q: "What color is Santa Claus's suit?", o: ["Red", "Blue", "Green", "Purple"], a: 0 },
    { c: "Christmas", q: "Where does Santa Claus live?", o: ["The North Pole", "The South Pole", "A castle", "An island"], a: 0 },
    { c: "Christmas", q: "What do children traditionally leave out for Santa on Christmas Eve?", o: ["Cookies and milk", "Sandwiches and juice", "Cake and tea", "Fruit and water"], a: 0 },
    { c: "Christmas", q: "What is the name of Santa's most famous red-nosed reindeer?", o: ["Rudolph", "Dasher", "Comet", "Blitzen"], a: 0 },
    { c: "Christmas", q: "What do people traditionally decorate with lights and ornaments at Christmas?", o: ["A Christmas tree", "A garden", "A car", "A cake"], a: 0 },
    { c: "Christmas", q: "What do people call Santa's little helpers who make toys?", o: ["Elves", "Fairies", "Gnomes", "Pixies"], a: 0 },
    { c: "Christmas", q: "What do people hang by the fireplace hoping Santa will fill with gifts?", o: ["Stockings", "Bags", "Baskets", "Boxes"], a: 0 },
    { c: "Christmas", q: "On what date is Christmas celebrated?", o: ["December 25th", "December 31st", "January 1st", "December 1st"], a: 0 },
    { c: "Christmas", q: "What plant do people traditionally kiss under at Christmas?", o: ["Mistletoe", "Holly", "Ivy", "Poinsettia"], a: 0 },
    { c: "Christmas", q: "How many reindeer, not counting Rudolph, traditionally pull Santa's sleigh?", o: ["Eight", "Six", "Ten", "Four"], a: 0 },
    { c: "Christmas", q: "What jingly Christmas song begins with \"Dashing through the snow\"?", o: ["Jingle Bells", "Silent Night", "Deck the Halls", "Frosty the Snowman"], a: 0 },
    { c: "Christmas", q: "What do people often build outside using snow in winter?", o: ["A snowman", "A sandcastle", "A tent", "A fort"], a: 0 },
    { c: "Christmas", q: "What striped sweet treat is often hung on Christmas trees?", o: ["A candy cane", "A lollipop", "A gummy bear", "A chocolate coin"], a: 0 },
    { c: "Christmas", q: "What does Santa Claus famously say to greet people?", o: ["Ho ho ho", "Fa la la", "Tada", "Abracadabra"], a: 0 },

    // --- Easter (10) ---
    { c: "Easter", q: "What animal is famous for delivering Easter eggs?", o: ["The Easter Bunny", "A chick", "A lamb", "A duck"], a: 0 },
    { c: "Easter", q: "What fun activity do kids do to find hidden decorated eggs?", o: ["An Easter egg hunt", "A treasure map", "A scavenger race", "A puzzle hunt"], a: 0 },
    { c: "Easter", q: "What sweet chocolate treat is often shaped like a bunny at Easter?", o: ["A chocolate bunny", "A chocolate Santa", "A chocolate pumpkin", "A chocolate heart"], a: 0 },
    { c: "Easter", q: "What small colorful candy often comes shaped like a tiny egg?", o: ["A jellybean", "A gumdrop", "A lollipop", "A marshmallow"], a: 0 },
    { c: "Easter", q: "What container do kids use to collect their Easter treats?", o: ["An Easter basket", "A backpack", "A jar", "A stocking"], a: 0 },
    { c: "Easter", q: "What season does Easter usually happen in the Northern Hemisphere?", o: ["Spring", "Winter", "Summer", "Autumn"], a: 0 },
    { c: "Easter", q: "What fluffy baby animal is often associated with Easter?", o: ["A baby chick", "A puppy", "A kitten", "A calf"], a: 0 },
    { c: "Easter", q: "What flower is often associated with Easter?", o: ["Lily", "Rose", "Tulip", "Daisy"], a: 0 },
    { c: "Easter", q: "What do people often decorate at Easter time using paint and dye?", o: ["Eggs", "Pumpkins", "Trees", "Cookies"], a: 0 },
    { c: "Easter", q: "What fuzzy-tailed animal hops around and is a symbol of Easter?", o: ["A rabbit", "A fox", "A deer", "A squirrel"], a: 0 },

    // --- Grinch (8) ---
    { c: "Grinch", q: "What color is the Grinch?", o: ["Green", "Blue", "Red", "Purple"], a: 0 },
    { c: "Grinch", q: "Where does the Grinch live?", o: ["On a mountain above Whoville", "In a cave by the sea", "Under a bridge", "In a big city"], a: 0 },
    { c: "Grinch", q: "What does the Grinch try to steal from the Whos?", o: ["Christmas", "Their pets", "Their gold", "Their food"], a: 0 },
    { c: "Grinch", q: "What is the name of the Grinch's loyal dog?", o: ["Max", "Rex", "Fido", "Buddy"], a: 0 },
    { c: "Grinch", q: "What cheerful town does the Grinch live near?", o: ["Whoville", "Springfield", "Bikini Bottom", "Seabrook"], a: 0 },
    { c: "Grinch", q: "What happens to the Grinch's heart at the end of the story?", o: ["It grows three sizes", "It turns to stone", "It shrinks away", "It freezes"], a: 0 },
    { c: "Grinch", q: "What costume does the Grinch wear to trick the Whos?", o: ["Santa Claus", "A snowman", "A reindeer", "An elf"], a: 0 },
    { c: "Grinch", q: "What is the title of the classic story about the Grinch stealing a holiday?", o: ["How the Grinch Stole Christmas!", "The Grinch's Big Day", "A Grinchy Winter", "Whoville Wonders"], a: 0 },

    // --- Dr. Seuss (9) ---
    { c: "Dr. Seuss", q: "Who wrote the classic book Green Eggs and Ham?", o: ["Dr. Seuss", "Roald Dahl", "Enid Blyton", "Beatrix Potter"], a: 0 },
    { c: "Dr. Seuss", q: "In Green Eggs and Ham, what strange food does the character refuse to try at first?", o: ["Green eggs and ham", "Blue pancakes", "Purple soup", "Pink spaghetti"], a: 0 },
    { c: "Dr. Seuss", q: "What Dr. Seuss book starts with the line \"One fish two fish\"?", o: ["One Fish Two Fish Red Fish Blue Fish", "Fox in Socks", "The Cat in the Hat", "Horton Hears a Who"], a: 0 },
    { c: "Dr. Seuss", q: "What tiny world does the elephant Horton protect in a Dr. Seuss book?", o: ["A speck of dust", "A flower", "A pond", "An egg"], a: 0 },
    { c: "Dr. Seuss", q: "What Dr. Seuss book is about protecting trees and nature?", o: ["The Lorax", "The Grinch", "Horton Hears a Who", "Fox in Socks"], a: 0 },
    { c: "Dr. Seuss", q: "Who famously says \"I speak for the trees\" in a Dr. Seuss book?", o: ["The Lorax", "Horton", "The Grinch", "The Cat in the Hat"], a: 0 },
    { c: "Dr. Seuss", q: "What Dr. Seuss book cheers kids on as they head out into the world?", o: ["Oh, the Places You'll Go!", "Green Eggs and Ham", "The Lorax", "Horton Hatches the Egg"], a: 0 },
    { c: "Dr. Seuss", q: "What silly Dr. Seuss book is famous for its tongue-twisting rhymes about a fox?", o: ["Fox in Socks", "The Cat in the Hat", "Horton Hears a Who", "The Lorax"], a: 0 },
    { c: "Dr. Seuss", q: "What was the real name of the author known as \"Dr. Seuss\"?", o: ["Theodor Geisel", "Roald Dahl", "Enid Blyton", "Maurice Sendak"], a: 0 },

    // --- Cat in the Hat (7) ---
    { c: "Cat in the Hat", q: "What does the Cat in the Hat wear on top of his head?", o: ["A tall red and white striped hat", "A green cap", "A crown", "A wizard hat"], a: 0 },
    { c: "Cat in the Hat", q: "What are the names of the two mischievous creatures the Cat lets out of a big box?", o: ["Thing One and Thing Two", "Tweedle Dee and Tweedle Dum", "Huey and Dewey", "Bert and Ernie"], a: 0 },
    { c: "Cat in the Hat", q: "What pet watches the children and worries about the mess the Cat makes?", o: ["The Fish", "The Dog", "The Cat's friend", "The Bird"], a: 0 },
    { c: "Cat in the Hat", q: "What does the Cat use to clean up the huge mess at the end of the story?", o: ["A special cleaning machine", "A magic broom", "A vacuum", "A mop"], a: 0 },
    { c: "Cat in the Hat", q: "What is the weather like outside while the story takes place?", o: ["Rainy", "Sunny", "Snowy", "Windy"], a: 0 },
    { c: "Cat in the Hat", q: "Who is home alone with her brother when the Cat visits?", o: ["Sally", "Lucy", "Jane", "Alice"], a: 0 },
    { c: "Cat in the Hat", q: "What does the Cat balance on one hand while standing on a ball?", o: ["A cake, a rake, and a fish", "A stack of books only", "A pile of toys", "A tower of blocks"], a: 0 },

    // --- Elf (8) ---
    { c: "Elf", q: "What is the name of the human raised as an elf in the movie Elf?", o: ["Buddy", "Walter", "Michael", "Charlie"], a: 0 },
    { c: "Elf", q: "Where was Buddy raised, believing he was an elf?", o: ["The North Pole", "New York City", "A small village", "A toy factory"], a: 0 },
    { c: "Elf", q: "According to Buddy, what are the four main food groups?", o: ["Candy, candy canes, candy corn, and syrup", "Fruits, vegetables, meat, and grains", "Cookies, cake, pie, and milk", "Bread, cheese, ham, and juice"], a: 0 },
    { c: "Elf", q: "What city does Buddy travel to in order to find his real father?", o: ["New York City", "Los Angeles", "Chicago", "Boston"], a: 0 },
    { c: "Elf", q: "What does Buddy famously pour all over his spaghetti?", o: ["Maple syrup", "Ketchup", "Chocolate sauce", "Honey"], a: 0 },
    { c: "Elf", q: "What is the name of Buddy's real father in the movie?", o: ["Walter Hobbs", "James Hobbs", "Michael Hobbs", "Robert Hobbs"], a: 0 },
    { c: "Elf", q: "What does Buddy shout excitedly when he sees Santa Claus?", o: ["'SANTA! I know him!'", "'Santa is real!'", "'It's Christmas!'", "'Ho ho ho!'"], a: 0 },
    { c: "Elf", q: "What does Buddy help save at the end of the movie, using Christmas spirit?", o: ["Santa's sleigh", "Santa's workshop", "The North Pole", "Christmas Eve"], a: 0 },

    // --- Lollies (8) ---
    { c: "Lollies", q: "What is another word for candy or sweets, often used in Australia and New Zealand?", o: ["Lollies", "Snacks", "Treats", "Munchies"], a: 0 },
    { c: "Lollies", q: "What long, chewy, colorful candy is shaped like a wiggly worm?", o: ["A gummy worm", "A licorice stick", "A candy cane", "A jawbreaker"], a: 0 },
    { c: "Lollies", q: "What hard candy on a stick do you lick until it disappears?", o: ["A lollipop", "A gumball", "A mint", "A caramel"], a: 0 },
    { c: "Lollies", q: "What small, colorful, chewy candy comes in a big bag with lots of flavors?", o: ["Jellybeans", "Marshmallows", "Toffees", "Chocolates"], a: 0 },
    { c: "Lollies", q: "What sweet treat has a caramel and nougat center covered in chocolate?", o: ["A chocolate bar", "A jellybean", "A lollipop", "A gumdrop"], a: 0 },
    { c: "Lollies", q: "What red and white striped candy is shaped like a walking stick?", o: ["A candy cane", "A peppermint", "A licorice twist", "A lollipop"], a: 0 },
    { c: "Lollies", q: "What kind of candy fizzes and pops on your tongue?", o: ["Popping candy", "Chewing gum", "Hard candy", "Marshmallows"], a: 0 },
    { c: "Lollies", q: "What stretchy, sticky candy do you chew for a long time but never swallow?", o: ["Chewing gum", "Toffee", "Fudge", "Caramel"], a: 0 },

    // --- Fairies (8) ---
    { c: "Fairies", q: "What is the name of the fairy in Peter Pan who is a little jealous of Wendy?", o: ["Tinker Bell", "Silky", "Periwinkle", "Rosetta"], a: 0 },
    { c: "Fairies", q: "What do fairies in stories often sprinkle to make magic happen?", o: ["Fairy dust", "Glitter glue", "Star sand", "Moon powder"], a: 0 },
    { c: "Fairies", q: "What magical winged creature grants wishes and casts spells with a wand?", o: ["A fairy", "A goblin", "A troll", "A dragon"], a: 0 },
    { c: "Fairies", q: "What fairy visits children at night when they lose a tooth?", o: ["The Tooth Fairy", "The Sandman", "The Sleep Fairy", "The Star Fairy"], a: 0 },
    { c: "Fairies", q: "Who is the magical fairy that helps Cinderella get ready for the ball?", o: ["The Fairy Godmother", "The Tooth Fairy", "Tinker Bell", "The Snow Queen"], a: 0 },
    { c: "Fairies", q: "What object do fairies typically use to cast their spells?", o: ["A magic wand", "A broomstick", "A crystal ball", "A magic mirror"], a: 0 },
    { c: "Fairies", q: "What tiny sparkly stuff do fairies leave behind when they fly by?", o: ["Fairy dust", "Rainbow dust", "Sparkle trail", "Moonlight"], a: 0 },
    { c: "Fairies", q: "In stories, what do fairies often use as a tiny umbrella or hat?", o: ["A flower petal", "A leaf boat", "A snail shell", "A pebble"], a: 0 },

    // --- Faraway Tree (8) ---
    { c: "Faraway Tree", q: "What is the name of the enormous magical tree in Enid Blyton's famous story?", o: ["The Faraway Tree", "The Wishing Tree", "The Whispering Tree", "The Enchanted Oak"], a: 0 },
    { c: "Faraway Tree", q: "What appears at the top of the Faraway Tree, changing every so often?", o: ["A different magical land", "A castle", "A rainbow bridge", "A treasure chest"], a: 0 },
    { c: "Faraway Tree", q: "What is the name of the grumpy pixie who lives partway up the tree?", o: ["The Angry Pixie", "The Grumpy Gnome", "The Cross Elf", "The Sour Sprite"], a: 0 },
    { c: "Faraway Tree", q: "What is the name of the friendly round-faced man who lives in the tree?", o: ["Moonface", "Saucepan Man", "Silky", "Watzisname"], a: 0 },
    { c: "Faraway Tree", q: "Who pours soapy water down the tree, soaking anyone below?", o: ["Dame Washalot", "The Angry Pixie", "Moonface", "Mister Watzisname"], a: 0 },
    { c: "Faraway Tree", q: "What does Moonface use to slide all the way down inside the tree?", o: ["A curly slide", "A rope ladder", "A magic elevator", "A giant leaf"], a: 0 },
    { c: "Faraway Tree", q: "What is the name of the forest where the Faraway Tree grows?", o: ["The Enchanted Wood", "Whispering Woods", "The Magic Grove", "Fernly Forest"], a: 0 },
    { c: "Faraway Tree", q: "Who wrote The Magic Faraway Tree?", o: ["Enid Blyton", "Roald Dahl", "Dr. Seuss", "Beatrix Potter"], a: 0 },

    // --- Ghostbusters (8) ---
    { c: "Ghostbusters", q: "What special equipment do the Ghostbusters wear on their backs to catch ghosts?", o: ["Proton packs", "Jetpacks", "Vacuum packs", "Rocket boosters"], a: 0 },
    { c: "Ghostbusters", q: "What is the famous phrase people say when they need the Ghostbusters?", o: ["'Who ya gonna call?'", "'Help is on the way!'", "'Ghosts beware!'", "'Call the squad!'"], a: 0 },
    { c: "Ghostbusters", q: "What is the name of the friendly green ghost the Ghostbusters often chase?", o: ["Slimer", "Boo", "Gooey", "Spook"], a: 0 },
    { c: "Ghostbusters", q: "What giant mascot comes to life and stomps through the city in the first movie?", o: ["The Stay Puft Marshmallow Man", "The Gingerbread Giant", "The Balloon Man", "The Snowman"], a: 0 },
    { c: "Ghostbusters", q: "What symbol represents the Ghostbusters team, with a ghost and a red line through it?", o: ["The no-ghost logo", "A skull and crossbones", "A lightning bolt", "A star"], a: 0 },
    { c: "Ghostbusters", q: "What special car do the Ghostbusters drive around town?", o: ["Ecto-1", "The Ghostmobile", "The Spook Wagon", "The Phantom Car"], a: 0 },
    { c: "Ghostbusters", q: "What device do the Ghostbusters use to trap a ghost once they catch it?", o: ["A ghost trap", "A ghost cage", "A spirit jar", "A soul box"], a: 0 },
    { c: "Ghostbusters", q: "What is the main job of the Ghostbusters?", o: ["Catching and removing ghosts", "Fighting monsters", "Building robots", "Exploring space"], a: 0 },

    // --- Toys (8) ---
    { c: "Toys", q: "What toy spins on a point and can balance while twirling around?", o: ["A top", "A yo-yo", "A marble", "A ball"], a: 0 },
    { c: "Toys", q: "What toy flies in the sky and is controlled with a long string?", o: ["A kite", "A balloon", "A frisbee", "A paper plane"], a: 0 },
    { c: "Toys", q: "What building toy is made of small colorful interlocking plastic bricks?", o: ["LEGO bricks", "Wooden blocks", "Puzzle pieces", "Magnetic tiles"], a: 0 },
    { c: "Toys", q: "What soft, cuddly stuffed toy is a classic bedtime companion for kids?", o: ["A teddy bear", "A rag doll", "A pillow pet", "A plush dinosaur"], a: 0 },
    { c: "Toys", q: "What round toy do you bounce, throw, and kick in lots of different games?", o: ["A ball", "A hoop", "A frisbee", "A balloon"], a: 0 },
    { c: "Toys", q: "What two-wheeled toy do kids push along with their feet before riding a bike?", o: ["A balance bike", "A tricycle", "A scooter", "A skateboard"], a: 0 },
    { c: "Toys", q: "What toy has a crank you turn until it suddenly pops open with a surprise?", o: ["A jack-in-the-box", "A music box", "A treasure chest", "A puppet"], a: 0 },
    { c: "Toys", q: "What string toy loops around your finger and you flip up and down?", o: ["A yo-yo", "A spinning top", "A paddle ball", "A slinky"], a: 0 },

    // --- Toy Story (10) ---
    { c: "Toy Story", q: "Who is the cowboy toy that belongs to Andy in Toy Story?", o: ["Woody", "Buzz Lightyear", "Rex", "Mr. Potato Head"], a: 0 },
    { c: "Toy Story", q: "Who is the space ranger action figure who becomes Andy's toy?", o: ["Buzz Lightyear", "Woody", "Slinky Dog", "Hamm"], a: 0 },
    { c: "Toy Story", q: "What is Buzz Lightyear's famous catchphrase?", o: ["'To infinity and beyond!'", "'Reach for the sky!'", "'You've got a friend in me!'", "'Blast off!'"], a: 0 },
    { c: "Toy Story", q: "What is the name of the neighbor kid who breaks toys apart?", o: ["Sid", "Al", "Chunk", "Buster"], a: 0 },
    { c: "Toy Story", q: "What toy is a stretchy dog with a spring for a body?", o: ["Slinky Dog", "Rex", "Bullseye", "Wheezy"], a: 0 },
    { c: "Toy Story", q: "What is the name of the yodeling cowgirl toy who joins Andy's group?", o: ["Jessie", "Bo Peep", "Barbie", "Dolly"], a: 0 },
    { c: "Toy Story", q: "Who is the grumpy potato-shaped toy with parts that can be rearranged?", o: ["Mr. Potato Head", "Hamm", "Rex", "Lenny"], a: 0 },
    { c: "Toy Story", q: "What daycare center do the toys end up at in Toy Story 3?", o: ["Sunnyside Daycare", "Happy Hills Daycare", "Rainbow Daycare", "Little Tykes Daycare"], a: 0 },
    { c: "Toy Story", q: "What homemade toy made from a spork and craft supplies appears in Toy Story 4?", o: ["Forky", "Ducky", "Bunny", "Combat Carl"], a: 0 },
    { c: "Toy Story", q: "What is the name of the boy who first owns Woody and Buzz?", o: ["Andy", "Sid", "Al", "Bonnie"], a: 0 },

    // --- Pixar (10) ---
    { c: "Pixar", q: "In Finding Nemo, what kind of fish is Nemo?", o: ["A clownfish", "A goldfish", "A shark", "A seahorse"], a: 0 },
    { c: "Pixar", q: "What is the name of Nemo's forgetful blue fish friend?", o: ["Dory", "Marlin", "Bruce", "Gill"], a: 0 },
    { c: "Pixar", q: "What does Carl use to make his house fly in the movie Up?", o: ["Balloons", "A rocket", "A giant fan", "A magic carpet"], a: 0 },
    { c: "Pixar", q: "What is the name of the robot who cleans up Earth in WALL-E?", o: ["WALL-E", "EVE", "R2-D2", "Baymax"], a: 0 },
    { c: "Pixar", q: "In Inside Out, what is the name of the cheerful yellow emotion inside Riley's head?", o: ["Joy", "Sadness", "Anger", "Fear"], a: 0 },
    { c: "Pixar", q: "What is the name of the rat who dreams of becoming a chef in Ratatouille?", o: ["Remy", "Linguini", "Emile", "Skinner"], a: 0 },
    { c: "Pixar", q: "What Pixar movie is about a family who secretly has superpowers?", o: ["The Incredibles", "Big Hero 6", "Cars", "Brave"], a: 0 },
    { c: "Pixar", q: "In Coco, what special family celebration is the story built around?", o: ["Día de los Muertos (Day of the Dead)", "Christmas", "A birthday party", "A wedding"], a: 0 },
    { c: "Pixar", q: "What Pixar movie takes place mostly in the world of talking race cars?", o: ["Cars", "Turbo", "Wreck-It Ralph", "Speed Racer"], a: 0 },
    { c: "Pixar", q: "What is the name of the big purple-blue furry monster in Monsters, Inc.?", o: ["Sulley", "Mike", "Randall", "Roz"], a: 0 },

    // --- Disney (15) ---
    { c: "Disney", q: "What is the name of the ice queen who can freeze anything she touches in Frozen?", o: ["Elsa", "Anna", "Rapunzel", "Belle"], a: 0 },
    { c: "Disney", q: "What is the name of Elsa's sister in Frozen?", o: ["Anna", "Moana", "Merida", "Tiana"], a: 0 },
    { c: "Disney", q: "What is the name of the friendly snowman who loves warm hugs in Frozen?", o: ["Olaf", "Sven", "Kristoff", "Marshmallow"], a: 0 },
    { c: "Disney", q: "What Disney princess sails the ocean to save her island?", o: ["Moana", "Ariel", "Pocahontas", "Jasmine"], a: 0 },
    { c: "Disney", q: "What is the name of the lion cub who becomes king in The Lion King?", o: ["Simba", "Mufasa", "Timon", "Nala"], a: 0 },
    { c: "Disney", q: "What does Aladdin fly on with Princess Jasmine?", o: ["A magic carpet", "A flying elephant", "A dragon", "A giant bird"], a: 0 },
    { c: "Disney", q: "What is the name of the mermaid princess who wishes to live on land?", o: ["Ariel", "Elsa", "Moana", "Tiana"], a: 0 },
    { c: "Disney", q: "What Disney princess falls into a deep sleep for 100 years?", o: ["Sleeping Beauty (Aurora)", "Snow White", "Cinderella", "Belle"], a: 0 },
    { c: "Disney", q: "What Disney princess has extremely long, magical golden hair?", o: ["Rapunzel", "Elsa", "Anna", "Merida"], a: 0 },
    { c: "Disney", q: "What Disney movie is about a girl with magical powers who lives in a colorful house in Colombia?", o: ["Encanto", "Coco", "Moana", "Luca"], a: 0 },
    { c: "Disney", q: "Who falls in love with a prince who was cursed to become a beast?", o: ["Belle", "Snow White", "Cinderella", "Jasmine"], a: 0 },
    { c: "Disney", q: "What Disney princess loses a glass slipper at a royal ball?", o: ["Cinderella", "Snow White", "Aurora", "Belle"], a: 0 },
    { c: "Disney", q: "What magical character grants three wishes in Aladdin?", o: ["The Genie", "The Sultan", "Jafar", "Abu"], a: 0 },
    { c: "Disney", q: "What Disney movie follows a warrior girl who joins the army disguised as a man?", o: ["Mulan", "Pocahontas", "Brave", "Moana"], a: 0 },
    { c: "Disney", q: "What Disney character is a flying baby elephant with giant ears?", o: ["Dumbo", "Baloo", "Simba", "Bambi"], a: 0 },

    // --- Pop Culture (8) ---
    { c: "Pop Culture", q: "What building and survival video game lets you create anything out of blocks?", o: ["Minecraft", "Roblox", "Fortnite", "Pokémon"], a: 0 },
    { c: "Pop Culture", q: "What loveable Australian cartoon dog is the star of her own hit TV show?", o: ["Bluey", "Peppa", "Chase", "Clifford"], a: 0 },
    { c: "Pop Culture", q: "What team of rescue puppies use cool vehicles to save the day in a popular show?", o: ["PAW Patrol", "Wonder Pets", "Octonauts", "Rescue Rangers"], a: 0 },
    { c: "Pop Culture", q: "What pocket monsters do trainers catch, train, and battle in a famous game and show?", o: ["Pokémon", "Digimon", "Yo-kai", "Monster Hunters"], a: 0 },
    { c: "Pop Culture", q: "What is the name of the yellow electric mouse who is the most famous Pokémon?", o: ["Pikachu", "Charmander", "Squirtle", "Bulbasaur"], a: 0 },
    { c: "Pop Culture", q: "What movie franchise features small plastic minifigures who build things from bricks?", o: ["The LEGO Movie", "Toy Story", "Wreck-It Ralph", "Ralph Breaks the Internet"], a: 0 },
    { c: "Pop Culture", q: "What famous mouse is the official mascot of the Disney company?", o: ["Mickey Mouse", "Jerry", "Stuart Little", "Speedy Gonzales"], a: 0 },
    { c: "Pop Culture", q: "What do you call a story told using moving pictures shown in a cinema?", o: ["A movie", "A comic", "A podcast", "A postcard"], a: 0 },

    // ===================== BATCH 2 (+300, for a total of 500) =====================

    // --- SpongeBob (+21) ---
    { c: "SpongeBob", q: "Who is SpongeBob's boating school teacher?", o: ["Mrs. Puff", "Sandy", "Mr. Krabs", "Squidward"], a: 0 },
    { c: "SpongeBob", q: "What color is SpongeBob?", o: ["Yellow", "Orange", "Green", "Pink"], a: 0 },
    { c: "SpongeBob", q: "What is the name of Plankton's computer wife?", o: ["Karen", "Sandy", "Pearl", "Mrs. Puff"], a: 0 },
    { c: "SpongeBob", q: "What instrument does Squidward love to play?", o: ["The clarinet", "The drums", "The guitar", "The trumpet"], a: 0 },
    { c: "SpongeBob", q: "What is the name of the amusement park in Bikini Bottom?", o: ["Glove World", "Krusty Land", "Bubble World", "Shell Park"], a: 0 },
    { c: "SpongeBob", q: "What do SpongeBob and Patrick love to blow using soap?", o: ["Bubbles", "Balloons", "Whistles", "Kites"], a: 0 },
    { c: "SpongeBob", q: "What award does SpongeBob often win at the Krusty Krab?", o: ["Employee of the Month", "Best Cook Trophy", "Golden Spatula", "Krab Star"], a: 0 },
    { c: "SpongeBob", q: "What US state is Sandy Cheeks originally from?", o: ["Texas", "Florida", "California", "Ohio"], a: 0 },
    { c: "SpongeBob", q: "What does Patrick Star live under?", o: ["A rock", "A shell", "A pineapple", "A boat"], a: 0 },
    { c: "SpongeBob", q: "What is SpongeBob's last name?", o: ["SquarePants", "Squarewheel", "Roundpants", "Krabs"], a: 0 },
    { c: "SpongeBob", q: "What kitchen tool does SpongeBob use to flip Krabby Patties?", o: ["A spatula", "A whisk", "A ladle", "A fork"], a: 0 },
    { c: "SpongeBob", q: "What does SpongeBob struggle to pass again and again at boating school?", o: ["His driving test", "His cooking exam", "His swimming test", "His spelling test"], a: 0 },
    { c: "SpongeBob", q: "What shape is Squidward's house?", o: ["A moai (stone head) shape", "A pineapple shape", "A shell shape", "A boat shape"], a: 0 },
    { c: "SpongeBob", q: "Who is the buff lifeguard at Goo Lagoon beach?", o: ["Larry the Lobster", "Mr. Krabs", "Squidward", "Patrick"], a: 0 },
    { c: "SpongeBob", q: "What is the name of the beach where Bikini Bottom characters relax?", o: ["Goo Lagoon", "Shell Beach", "Coral Bay", "Bubble Shore"], a: 0 },
    { c: "SpongeBob", q: "What ghost pirate is said to haunt Bikini Bottom?", o: ["The Flying Dutchman", "Blackbeard", "Davy Jones", "Captain Hook"], a: 0 },
    { c: "SpongeBob", q: "What is the name of Plankton's restaurant, rival to the Krusty Krab?", o: ["The Chum Bucket", "The Kelp Shack", "The Bubble Cafe", "The Krab Shack"], a: 0 },
    { c: "SpongeBob", q: "What does Mr. Krabs love more than almost anything?", o: ["Money", "Jellyfishing", "Karate", "Napping"], a: 0 },
    { c: "SpongeBob", q: "What does Squidward often dream of becoming, besides a Krusty Krab cashier?", o: ["A famous artist", "A boat captain", "A chef", "A teacher"], a: 0 },
    { c: "SpongeBob", q: "What tiny one-eyed creature is Plankton?", o: ["A copepod", "A shrimp", "A crab", "A snail"], a: 0 },
    { c: "SpongeBob", q: "What martial art do SpongeBob and Sandy love to practice together?", o: ["Karate", "Judo", "Boxing", "Fencing"], a: 0 },

    // --- TMNT (+18) ---
    { c: "TMNT", q: "What is the name of the ninja clan led by the turtles' enemy Shredder?", o: ["The Foot Clan", "The Hand Clan", "The Shadow Clan", "The Claw Clan"], a: 0 },
    { c: "TMNT", q: "What weapon does Leonardo fight with?", o: ["Twin katana swords", "Nunchaku", "A bo staff", "Sais"], a: 0 },
    { c: "TMNT", q: "What weapon does Michelangelo fight with?", o: ["Nunchaku", "Twin katana swords", "A bo staff", "Sais"], a: 0 },
    { c: "TMNT", q: "What weapon does Donatello fight with?", o: ["A bo staff", "Nunchaku", "Sais", "Twin katana swords"], a: 0 },
    { c: "TMNT", q: "What kind of animal is Splinter?", o: ["A rat", "A raccoon", "A mouse", "A hamster"], a: 0 },
    { c: "TMNT", q: "What is the name of the turtles' vigilante ally who wears a hockey mask?", o: ["Casey Jones", "April O'Neil", "Vernon", "Baxter Stockman"], a: 0 },
    { c: "TMNT", q: "What mysterious substance turned the turtles and Splinter into mutants?", o: ["Mutagen ooze", "Magic potion", "Radioactive water", "Alien dust"], a: 0 },
    { c: "TMNT", q: "What are Shredder's robotic or ninja henchmen usually called?", o: ["Foot Soldiers", "Shadow Guards", "Iron Ninjas", "Steel Warriors"], a: 0 },
    { c: "TMNT", q: "How is Michelangelo's personality usually described?", o: ["Fun-loving and goofy", "Tough and hot-tempered", "Disciplined and serious", "Shy and quiet"], a: 0 },
    { c: "TMNT", q: "What is Donatello best known for building?", o: ["Gadgets and machines", "Weapons for battle", "Pizza recipes", "Skateboards"], a: 0 },
    { c: "TMNT", q: "How is Raphael's personality usually described?", o: ["Tough and hot-tempered", "Fun-loving and goofy", "Calm and quiet", "Nerdy and shy"], a: 0 },
    { c: "TMNT", q: "How is Leonardo's personality usually described?", o: ["Disciplined and responsible", "Silly and careless", "Grumpy and lazy", "Shy and nervous"], a: 0 },
    { c: "TMNT", q: "What short name is often used for the Teenage Mutant Ninja Turtles?", o: ["TMNT", "TNMT", "NMTT", "MNTT"], a: 0 },
    { c: "TMNT", q: "Who trains the turtles in the art of ninjutsu?", o: ["Splinter", "Shredder", "Casey Jones", "April"], a: 0 },
    { c: "TMNT", q: "What color is the turtles' skin?", o: ["Green", "Blue", "Brown", "Grey"], a: 0 },
    { c: "TMNT", q: "How many fingers does each turtle typically have on each hand?", o: ["Three", "Two", "Four", "Five"], a: 0 },
    { c: "TMNT", q: "What is the turtles' famous excited battle cry?", o: ["'Cowabunga!'", "'Booyah!'", "'To the sewers!'", "'Turtle power, go!'"], a: 0 },
    { c: "TMNT", q: "What do the turtles often run across to travel quickly through the city?", o: ["Rooftops", "Bridges", "Subway tunnels", "Highways"], a: 0 },

    // --- Zombies (+12) ---
    { c: "Zombies", q: "What is the name of Addison's football-star cousin in ZOMBIES?", o: ["Bucky", "Zed", "Bonzo", "Wyatt"], a: 0 },
    { c: "Zombies", q: "What is the name of the cheer captain who becomes Addison's friend?", o: ["Bree", "Eliza", "Willa", "Zoey"], a: 0 },
    { c: "Zombies", q: "What is the title of the sequel movie that introduces more werewolf characters?", o: ["ZOMBIES 2", "ZOMBIES 3", "ZOMBIES: Werewolves", "ZOMBIES Returns"], a: 0 },
    { c: "Zombies", q: "What color are the zombies' eyes usually shown as?", o: ["Green", "Red", "Yellow", "Blue"], a: 0 },
    { c: "Zombies", q: "What is the mascot/team name of Seabrook High's sports teams?", o: ["The Mighty Shrimp", "The Sea Lions", "The Zombies", "The Wolves"], a: 0 },
    { c: "Zombies", q: "Why does Zed want to join the football team?", o: ["To prove zombies can fit in", "To become famous", "To impress Bree", "To win a scholarship"], a: 0 },
    { c: "Zombies", q: "Besides acting, what do the ZOMBIES movies feature a lot of?", o: ["Singing and dancing", "Sports commentary", "Cooking competitions", "Magic tricks"], a: 0 },
    { c: "Zombies", q: "What TV channel made the ZOMBIES movies?", o: ["Disney Channel", "Cartoon Network", "Nickelodeon", "PBS Kids"], a: 0 },
    { c: "Zombies", q: "What activity is Addison most passionate about?", o: ["Cheerleading", "Football", "Painting", "Swimming"], a: 0 },
    { c: "Zombies", q: "What color does Addison dye her hair to fit in with the other cheerleaders?", o: ["Pink", "Blue", "Purple", "Green"], a: 0 },
    { c: "Zombies", q: "What type of school is Seabrook High?", o: ["A high school", "A boarding school", "An elementary school", "A college"], a: 0 },
    { c: "Zombies", q: "What is a central theme of the ZOMBIES movies?", o: ["Friendship between different groups", "Winning at all costs", "Ghosts haunting a town", "Time travel"], a: 0 },

    // --- Descendants (+12) ---
    { c: "Descendants", q: "What school do Mal, Evie, Carlos, and Jay attend once in Auradon?", o: ["Auradon Prep", "Isle Academy", "Auradon High", "Villain University"], a: 0 },
    { c: "Descendants", q: "Who is Ben's father, formerly known as the Beast?", o: ["King Beast (Adam)", "King Triton", "King Stefan", "The Sultan"], a: 0 },
    { c: "Descendants", q: "Who is Ben's mother, a former human turned princess?", o: ["Belle", "Snow White", "Cinderella", "Aurora"], a: 0 },
    { c: "Descendants", q: "What is Evie especially skilled and passionate about?", o: ["Fashion design", "Sword fighting", "Cooking", "Painting"], a: 0 },
    { c: "Descendants", q: "What is the name of Carlos's pet dog?", o: ["Dude", "Max", "Rex", "Buddy"], a: 0 },
    { c: "Descendants", q: "What does Uma become captain of?", o: ["A pirate ship", "A sports team", "A royal guard", "A dance troupe"], a: 0 },
    { c: "Descendants", q: "What color is Mal's hair?", o: ["Purple", "Blue", "Red", "Blonde"], a: 0 },
    { c: "Descendants", q: "What type of film are the Descendants movies, full of singing and dancing?", o: ["A musical", "A documentary", "A silent film", "A puppet show"], a: 0 },
    { c: "Descendants", q: "What sport is popular at Auradon Prep?", o: ["Tourney", "Football", "Basketball", "Tennis"], a: 0 },
    { c: "Descendants", q: "What role does Jay earn on the Auradon Prep sports team?", o: ["Team captain", "Water boy", "Referee", "Coach"], a: 0 },
    { c: "Descendants", q: "What protects Auradon from the villains trapped on the Isle of the Lost?", o: ["A magical barrier", "A giant wall", "An army of knights", "A moat"], a: 0 },
    { c: "Descendants", q: "What classic fairy tale is Evie's mother, the Evil Queen, originally from?", o: ["Snow White", "Cinderella", "Sleeping Beauty", "Beauty and the Beast"], a: 0 },

    // --- Simpsons (+21) ---
    { c: "Simpsons", q: "What is the name of Homer Simpson's wife?", o: ["Marge", "Maggie", "Patty", "Selma"], a: 0 },
    { c: "Simpsons", q: "What is unusual about Marge Simpson's hair?", o: ["It's tall and blue", "It's bright red and curly", "It's very short", "It's covered by a hat"], a: 0 },
    { c: "Simpsons", q: "What grade is Bart Simpson in at school?", o: ["4th grade", "1st grade", "6th grade", "8th grade"], a: 0 },
    { c: "Simpsons", q: "What school do Bart and Lisa attend?", o: ["Springfield Elementary School", "Springfield High School", "Shelbyville Elementary", "Ogdenville Academy"], a: 0 },
    { c: "Simpsons", q: "What is the name of Homer's father, Bart's grandfather?", o: ["Abraham Simpson", "Herbert Simpson", "Clancy Bouvier", "Hyman Krustofsky"], a: 0 },
    { c: "Simpsons", q: "What are the names of Marge's two sisters?", o: ["Patty and Selma", "Ruth and Edna", "Helen and Luann", "Maude and Mabel"], a: 0 },
    { c: "Simpsons", q: "How old is Lisa Simpson?", o: ["8 years old", "5 years old", "12 years old", "6 years old"], a: 0 },
    { c: "Simpsons", q: "How old is Bart Simpson?", o: ["10 years old", "8 years old", "13 years old", "7 years old"], a: 0 },
    { c: "Simpsons", q: "What is the name of the bar Homer often visits with his friends?", o: ["Moe's Tavern", "The Springfield Pub", "Duff Gardens", "The Legion Hall"], a: 0 },
    { c: "Simpsons", q: "Who is the bartender at Homer's favorite bar?", o: ["Moe Szyslak", "Barney Gumble", "Lenny Leonard", "Carl Carlson"], a: 0 },
    { c: "Simpsons", q: "Who is Homer's boss at the nuclear power plant?", o: ["Mr. Burns", "Mayor Quimby", "Principal Skinner", "Chief Wiggum"], a: 0 },
    { c: "Simpsons", q: "Who is Mr. Burns's loyal assistant?", o: ["Waylon Smithers", "Lenny Leonard", "Carl Carlson", "Moe Szyslak"], a: 0 },
    { c: "Simpsons", q: "What is the name of the convenience store run by Apu?", o: ["The Kwik-E-Mart", "The Quick Stop", "The Corner Shop", "The Handy Mart"], a: 0 },
    { c: "Simpsons", q: "What is one of Bart Simpson's famous catchphrases?", o: ["'Eat my shorts!'", "'To infinity and beyond!'", "'Yabba dabba doo!'", "'Cowabunga!'"], a: 0 },
    { c: "Simpsons", q: "What special diet does Lisa follow because she cares about animals?", o: ["Vegetarian", "Gluten-free", "Dairy-free", "Sugar-free"], a: 0 },
    { c: "Simpsons", q: "Who is Springfield's well-known TV news anchor?", o: ["Kent Brockman", "Troy McClure", "Krusty the Clown", "Sideshow Bob"], a: 0 },
    { c: "Simpsons", q: "What color is Marge Simpson's dress?", o: ["Green", "Red", "Blue", "Yellow"], a: 0 },
    { c: "Simpsons", q: "How many children do Homer and Marge Simpson have?", o: ["Three", "Two", "Four", "Five"], a: 0 },
    { c: "Simpsons", q: "What does baby Maggie Simpson almost always have in her mouth?", o: ["A pacifier", "A bottle", "A teething ring", "A lollipop"], a: 0 },
    { c: "Simpsons", q: "What violent cartoon show do Bart and Lisa love to watch?", o: ["Itchy & Scratchy", "Tom & Jerry", "Looney Tunes", "Angry Beavers"], a: 0 },
    { c: "Simpsons", q: "What is the nickname of Springfield's comic book store owner?", o: ["Comic Book Guy", "The Collector", "Nerd Man", "Mr. Comics"], a: 0 },

    // --- Spirited Away (+10) ---
    { c: "Spirited Away", q: "What is the name of Yubaba's twin sister?", o: ["Zeniba", "Lin", "Kamaji", "Chihiro"], a: 0 },
    { c: "Spirited Away", q: "What is the name of the giant baby in Yubaba's chambers?", o: ["Boh", "Haku", "No-Face", "Kamaji"], a: 0 },
    { c: "Spirited Away", q: "What is No-Face known for offering people?", o: ["Gold", "Riddles", "Food", "Magic charms"], a: 0 },
    { c: "Spirited Away", q: "What is the name of the boiler man who runs the boiler room?", o: ["Kamaji", "Haku", "Zeniba", "Boh"], a: 0 },
    { c: "Spirited Away", q: "What job does Chihiro get at the bathhouse to survive?", o: ["A bathhouse worker", "A cook", "A guard", "A musician"], a: 0 },
    { c: "Spirited Away", q: "What must Chihiro sign to work at the bathhouse, which takes away part of her identity?", o: ["A contract", "A map", "A letter", "A scroll"], a: 0 },
    { c: "Spirited Away", q: "What new name does Yubaba give Chihiro?", o: ["Sen", "Boh", "Lin", "Zeniba"], a: 0 },
    { c: "Spirited Away", q: "What is Boh turned into for part of the film?", o: ["A mouse", "A frog", "A bird", "A pig"], a: 0 },
    { c: "Spirited Away", q: "What mode of transportation do Chihiro and her friends take across the flooded tracks?", o: ["A train", "A boat", "A bicycle", "A carriage"], a: 0 },
    { c: "Spirited Away", q: "Who directed Spirited Away?", o: ["Hayao Miyazaki", "Isao Takahata", "Makoto Shinkai", "Mamoru Hosoda"], a: 0 },

    // --- Christmas (+23) ---
    { c: "Christmas", q: "What is the name of Santa's wife?", o: ["Mrs. Claus", "Mother Christmas", "Mrs. Frost", "Mrs. Noel"], a: 0 },
    { c: "Christmas", q: "What do people often place on top of a Christmas tree?", o: ["A star or an angel", "A bow", "A candy cane", "A snowman"], a: 0 },
    { c: "Christmas", q: "What classic song mentions 'chestnuts roasting on an open fire'?", o: ["The Christmas Song", "Silent Night", "Jingle Bells", "Deck the Halls"], a: 0 },
    { c: "Christmas", q: "What is the name of Santa's reindeer whose name means 'thunder'?", o: ["Donner", "Blitzen", "Comet", "Dasher"], a: 0 },
    { c: "Christmas", q: "What is the day before Christmas called?", o: ["Christmas Eve", "Christmas Morning", "Yule Day", "Advent Day"], a: 0 },
    { c: "Christmas", q: "What classic song counts down gifts like 'a partridge in a pear tree'?", o: ["The Twelve Days of Christmas", "Jingle Bells", "Deck the Halls", "Joy to the World"], a: 0 },
    { c: "Christmas", q: "What do people traditionally do with a Yule log?", o: ["Burn it in the fireplace", "Decorate it with lights", "Give it as a gift", "Bury it in the yard"], a: 0 },
    { c: "Christmas", q: "What chocolate dessert is shaped like a log at Christmas?", o: ["A Yule log cake", "A gingerbread house", "A fruitcake", "A candy cane cookie"], a: 0 },
    { c: "Christmas", q: "What does an Advent calendar help children do?", o: ["Count down the days until Christmas", "Learn Christmas carols", "Wrap presents", "Write letters to Santa"], a: 0 },
    { c: "Christmas", q: "What color are holly berries usually?", o: ["Red", "Blue", "Yellow", "Purple"], a: 0 },
    { c: "Christmas", q: "What evergreen plant with red berries is a popular Christmas decoration?", o: ["Holly", "Ivy", "Fern", "Cactus"], a: 0 },
    { c: "Christmas", q: "What creamy spiced drink is popular at Christmas time?", o: ["Eggnog", "Lemonade", "Iced tea", "Root beer"], a: 0 },
    { c: "Christmas", q: "What animals pull Santa's sleigh?", o: ["Reindeer", "Horses", "Huskies", "Ponies"], a: 0 },
    { c: "Christmas", q: "What treat do people often leave out for Santa's reindeer?", o: ["Carrots", "Cheese", "Bread", "Apples"], a: 0 },
    { c: "Christmas", q: "What classic story features a boy riding a magical train to the North Pole?", o: ["The Polar Express", "The Grinch", "A Christmas Carol", "Frosty the Snowman"], a: 0 },
    { c: "Christmas", q: "What classic Charles Dickens story features Ebenezer Scrooge?", o: ["A Christmas Carol", "Oliver Twist", "Great Expectations", "A Tale of Two Cities"], a: 0 },
    { c: "Christmas", q: "What ghost first visits Scrooge in A Christmas Carol?", o: ["Jacob Marley", "The Ghost of Christmas Past", "The Ghost of Christmas Present", "The Ghost of Christmas Future"], a: 0 },
    { c: "Christmas", q: "What do carolers do at Christmas time?", o: ["Sing Christmas songs door to door", "Bake gingerbread houses", "Decorate trees for neighbors", "Deliver presents secretly"], a: 0 },
    { c: "Christmas", q: "What shape is a Christmas wreath traditionally?", o: ["A circle", "A square", "A star", "A triangle"], a: 0 },
    { c: "Christmas", q: "What spiced cookie shaped like a person is popular at Christmas?", o: ["A gingerbread man", "A sugar cookie", "A shortbread star", "A candy cane cookie"], a: 0 },
    { c: "Christmas", q: "What classic character is a snowman who comes to life wearing a magic hat?", o: ["Frosty the Snowman", "Olaf", "Snowy", "Jack Frost"], a: 0 },
    { c: "Christmas", q: "What is the name of the place at the North Pole where toys are made?", o: ["Santa's workshop", "The Elf Factory", "Toy Town", "Wonderland"], a: 0 },
    { c: "Christmas", q: "Besides Jacob Marley, how many ghosts visit Scrooge in A Christmas Carol?", o: ["Three", "One", "Two", "Four"], a: 0 },

    // --- Easter (+15) ---
    { c: "Easter", q: "What does the Christian holiday of Easter celebrate?", o: ["The resurrection of Jesus", "The birth of Jesus", "The first day of spring", "A great harvest"], a: 0 },
    { c: "Easter", q: "What do many people attend early in the morning on Easter?", o: ["A sunrise service", "A parade", "A picnic", "A concert"], a: 0 },
    { c: "Easter", q: "What do people wear on their heads at a traditional Easter parade?", o: ["Easter bonnets (hats)", "Party crowns", "Flower crowns only", "Scarves"], a: 0 },
    { c: "Easter", q: "What are small chocolate Easter eggs often wrapped in?", o: ["Colorful foil", "Tissue paper", "Cloth", "Cardboard"], a: 0 },
    { c: "Easter", q: "What do people typically use to color and decorate Easter eggs?", o: ["Dye and paint", "Glitter glue only", "Chalk", "Markers only"], a: 0 },
    { c: "Easter", q: "What popular marshmallow Easter candy is shaped like a chick or bunny?", o: ["Peeps", "Gummy bears", "Jelly Babies", "Marshmallow Pops"], a: 0 },
    { c: "Easter", q: "What famous annual Easter event takes place on the White House lawn?", o: ["The Easter Egg Roll", "The Easter Parade", "The Great Egg Hunt", "The Bunny Ball"], a: 0 },
    { c: "Easter", q: "What does the Easter Bunny supposedly hide around the house or yard?", o: ["Eggs and treats", "Toys and books", "Flowers", "Coins"], a: 0 },
    { c: "Easter", q: "What is the 40-day period of reflection before Easter called?", o: ["Lent", "Advent", "The Fast", "Holy Week"], a: 0 },
    { c: "Easter", q: "What day of the week does Easter always fall on?", o: ["Sunday", "Saturday", "Friday", "Monday"], a: 0 },
    { c: "Easter", q: "What is the Friday before Easter called?", o: ["Good Friday", "Holy Friday", "Silent Friday", "Palm Friday"], a: 0 },
    { c: "Easter", q: "What do many families do together on Easter Sunday?", o: ["Attend church and gather as a family", "Go trick-or-treating", "Watch fireworks", "Go camping"], a: 0 },
    { c: "Easter", q: "What meal do many families traditionally eat together on Easter?", o: ["Ham", "Turkey", "Pizza", "Pancakes"], a: 0 },
    { c: "Easter", q: "What classic egg-shaped chocolate treat has a soft, gooey center?", o: ["A creme egg", "A gummy egg", "A caramel egg bar", "A marshmallow egg"], a: 0 },
    { c: "Easter", q: "What must happen for a baby chick to hatch from its egg?", o: ["It pecks its way out of the shell", "Someone cracks it open", "It waits for rain", "The sun warms it open"], a: 0 },

    // --- Grinch (+10) ---
    { c: "Grinch", q: "What is the name of the mountain the Grinch lives on?", o: ["Mount Crumpit", "Mount Whoville", "Snowy Peak", "Grump Mountain"], a: 0 },
    { c: "Grinch", q: "What does the Grinch use to sneak into Whoville and steal presents?", o: ["A homemade sleigh", "A helicopter", "A secret tunnel", "A hot air balloon"], a: 0 },
    { c: "Grinch", q: "What young Who girl catches the Grinch in the act of stealing?", o: ["Cindy Lou Who", "Lucy Who", "Grinchy Who", "Sally Who"], a: 0 },
    { c: "Grinch", q: "What does the Grinch disguise Max as to pull his sled?", o: ["A reindeer", "A horse", "A husky", "A goat"], a: 0 },
    { c: "Grinch", q: "What do the Whos do every year that confuses the Grinch, even without presents?", o: ["They still sing and celebrate", "They cry all day", "They move away", "They hide indoors"], a: 0 },
    { c: "Grinch", q: "What does the Grinch return to the Whos after his heart grows?", o: ["All their presents and decorations", "Only the toys", "Half of the presents", "Just the Christmas tree"], a: 0 },
    { c: "Grinch", q: "Who wrote the original story of the Grinch?", o: ["Dr. Seuss", "Roald Dahl", "Enid Blyton", "Beatrix Potter"], a: 0 },
    { c: "Grinch", q: "What is the Grinch's attitude toward Christmas at the start of the story?", o: ["He hates it", "He loves it", "He ignores it", "He is confused by it"], a: 0 },
    { c: "Grinch", q: "What happens to the Grinch's heart at the very end of the story?", o: ["It grows three sizes", "It turns to ice", "It stops beating", "It shrinks away"], a: 0 },
    { c: "Grinch", q: "What holiday does the Grinch try to ruin every single year?", o: ["Christmas", "Halloween", "Easter", "Thanksgiving"], a: 0 },

    // --- Dr. Seuss (+13) ---
    { c: "Dr. Seuss", q: "What Dr. Seuss book features a character named Sam-I-Am?", o: ["Green Eggs and Ham", "The Cat in the Hat", "Horton Hears a Who", "The Lorax"], a: 0 },
    { c: "Dr. Seuss", q: "What Dr. Seuss book is about a boy imagining wild things on his way home from school?", o: ["And to Think That I Saw It on Mulberry Street", "Oh, the Places You'll Go!", "Fox in Socks", "The Sneetches"], a: 0 },
    { c: "Dr. Seuss", q: "What Dr. Seuss book features creatures called Sneetches, some with stars on their bellies?", o: ["The Sneetches", "Horton Hatches the Egg", "The Lorax", "Green Eggs and Ham"], a: 0 },
    { c: "Dr. Seuss", q: "What tiny town does Horton protect, living on a speck of dust?", o: ["Whoville", "Seussville", "Sneetchtown", "Lorax City"], a: 0 },
    { c: "Dr. Seuss", q: "What Dr. Seuss character hatches an egg after sitting on it for a very long time?", o: ["Horton", "The Lorax", "The Cat", "Sam-I-Am"], a: 0 },
    { c: "Dr. Seuss", q: "What does the Once-ler regret doing to the truffula trees?", o: ["Cutting them all down", "Painting them", "Planting too many", "Watering them too much"], a: 0 },
    { c: "Dr. Seuss", q: "What are the fuzzy little creatures who live among the truffula trees called?", o: ["Bar-ba-loots", "Sneetches", "Whos", "Grinches"], a: 0 },
    { c: "Dr. Seuss", q: "What two kinds of fish are named in the title of a famous Dr. Seuss counting book?", o: ["Red fish, blue fish", "Big fish, small fish", "Gold fish, black fish", "Fast fish, slow fish"], a: 0 },
    { c: "Dr. Seuss", q: "What does the fox wear in the tongue-twisting book Fox in Socks?", o: ["Socks", "Boots", "Sandals", "Slippers"], a: 0 },
    { c: "Dr. Seuss", q: "What does 'Oh, the Places You'll Go!' encourage readers to do?", o: ["Go out and achieve great things", "Stay home and rest", "Avoid new adventures", "Learn to cook"], a: 0 },
    { c: "Dr. Seuss", q: "What is unusual about the way Dr. Seuss's characters and creatures usually look?", o: ["They are wild, silly, made-up creatures", "They look like real animals", "They are always robots", "They look like ordinary people"], a: 0 },
    { c: "Dr. Seuss", q: "What Dr. Seuss book features a turtle king who stacks other turtles to build a taller throne?", o: ["Yertle the Turtle", "Horton Hears a Who", "The Lorax", "The Sneetches"], a: 0 },
    { c: "Dr. Seuss", q: "What is a hallmark of Dr. Seuss's writing style?", o: ["Rhyming verse with silly made-up words", "Long, serious paragraphs", "No pictures at all", "Only true stories"], a: 0 },

    // --- Cat in the Hat (+8) ---
    { c: "Cat in the Hat", q: "What does the Fish keep worrying about throughout the story?", o: ["That their mother will be upset about the mess", "That it will rain forever", "That the Cat will leave", "That the children will get hungry"], a: 0 },
    { c: "Cat in the Hat", q: "What does the Cat promise to show the children?", o: ["Fun and games", "A magic trick book", "A new pet", "A secret treehouse"], a: 0 },
    { c: "Cat in the Hat", q: "What jumps out of the big red box the Cat brings inside?", o: ["Thing One and Thing Two", "A pair of kittens", "Two puppies", "Two robots"], a: 0 },
    { c: "Cat in the Hat", q: "What do Thing One and Thing Two fly around the house?", o: ["Kites", "Balloons", "Paper planes", "Frisbees"], a: 0 },
    { c: "Cat in the Hat", q: "Who wrote The Cat in the Hat?", o: ["Dr. Seuss", "Roald Dahl", "Enid Blyton", "Maurice Sendak"], a: 0 },
    { c: "Cat in the Hat", q: "What do the children worry their mother will feel if she sees the mess?", o: ["Upset or angry", "Excited", "Proud", "Sleepy"], a: 0 },
    { c: "Cat in the Hat", q: "Where does the Fish live?", o: ["A fishbowl", "A pond", "A bathtub", "A bucket"], a: 0 },
    { c: "Cat in the Hat", q: "When do the children's mother come home, relative to the mess being cleaned up?", o: ["Just in time, right after it's cleaned", "Long before the mess starts", "The next day", "She never comes home in the story"], a: 0 },

    // --- Elf (+10) ---
    { c: "Elf", q: "What is the name of the woman Buddy falls in love with at the department store?", o: ["Jovie", "Susan", "Emily", "Zooey"], a: 0 },
    { c: "Elf", q: "What store does Buddy get a job decorating in New York?", o: ["Gimbels", "Macy's", "Toys R Us", "Bloomingdale's"], a: 0 },
    { c: "Elf", q: "What does Buddy believe is needed to make Santa's sleigh fly?", o: ["Christmas spirit", "Magic dust", "Reindeer food", "A special engine"], a: 0 },
    { c: "Elf", q: "What is the name of Buddy's human half-brother?", o: ["Michael", "Charlie", "Timmy", "David"], a: 0 },
    { c: "Elf", q: "What job does Buddy have at the North Pole before leaving for New York?", o: ["Toymaker elf", "Reindeer trainer", "Cookie baker", "Mail sorter"], a: 0 },
    { c: "Elf", q: "What kind of hat does Buddy wear as part of his elf costume?", o: ["A pointy elf hat", "A top hat", "A baseball cap", "A beanie"], a: 0 },
    { c: "Elf", q: "What does Buddy get overjoyed and shout about at the department store?", o: ["That Santa is coming", "That it's snowing", "That he got a raise", "That Christmas is cancelled"], a: 0 },
    { c: "Elf", q: "What actor played Buddy the Elf in the movie?", o: ["Will Ferrell", "Jim Carrey", "Steve Carell", "Adam Sandler"], a: 0 },
    { c: "Elf", q: "What do the elves at the North Pole spend all their time doing?", o: ["Making toys", "Baking cookies", "Training reindeer", "Writing letters"], a: 0 },
    { c: "Elf", q: "What food does Buddy love so much he eats it constantly throughout the movie?", o: ["Candy and sweets", "Vegetables", "Soup", "Fruit salad"], a: 0 },

    // --- Lollies (+10) ---
    { c: "Lollies", q: "What creamy white candy features cute little printed messages, popular on Valentine's Day?", o: ["Conversation hearts", "Jellybeans", "Marshmallows", "Fudge"], a: 0 },
    { c: "Lollies", q: "What black or red licorice-flavored candy comes in long twisted ropes?", o: ["Licorice", "Toffee", "Fudge", "Caramel"], a: 0 },
    { c: "Lollies", q: "What chewy candy is often shaped like a bear and comes in fruity flavors?", o: ["Gummy bears", "Jellybeans", "Marshmallows", "Toffees"], a: 0 },
    { c: "Lollies", q: "What kind of candy makes your mouth pucker up because it's so tart?", o: ["Sour candy", "Chocolate", "Marshmallow", "Toffee"], a: 0 },
    { c: "Lollies", q: "What kind of chocolate bar has crispy wafer layers inside?", o: ["A wafer chocolate bar", "A fudge bar", "A caramel bar", "A marshmallow bar"], a: 0 },
    { c: "Lollies", q: "What small, round, colorful chocolate candy is famous for melting 'in your mouth, not in your hand'?", o: ["M&M's", "Skittles", "Jellybeans", "Gumdrops"], a: 0 },
    { c: "Lollies", q: "What is a very large, hard candy that takes a long time to finish called?", o: ["A jawbreaker", "A lollipop", "A gumdrop", "A caramel"], a: 0 },
    { c: "Lollies", q: "What chewy, fruit-flavored candy comes individually wrapped in twisted paper?", o: ["Chewy fruit candy (like Starburst)", "Chocolate coins", "Candy canes", "Popping candy"], a: 0 },
    { c: "Lollies", q: "What is cotton candy also known as in Australia and the UK?", o: ["Fairy floss", "Sugar cloud", "Sweet fluff", "Spun sugar"], a: 0 },
    { c: "Lollies", q: "What frozen treat on a stick is popular in summer, known as an 'icy pole' in Australia?", o: ["A popsicle (icy pole)", "A snow cone", "A milkshake", "An ice cream sandwich"], a: 0 },

    // --- Fairies (+12) ---
    { c: "Fairies", q: "What is the name of Peter Pan's magical island home?", o: ["Neverland", "Wonderland", "Fairyland", "Sherwood Forest"], a: 0 },
    { c: "Fairies", q: "In the story of Peter Pan, what must you do to help a dying fairy?", o: ["Clap if you believe in fairies", "Sing a lullaby", "Sprinkle fairy dust", "Make a wish"], a: 0 },
    { c: "Fairies", q: "What tiny flying creature often helps guide travelers in fairy tales?", o: ["A fairy", "A troll", "A goblin", "An ogre"], a: 0 },
    { c: "Fairies", q: "What do fairies typically have on their backs that let them fly?", o: ["Wings", "A broomstick", "A cape", "A balloon"], a: 0 },
    { c: "Fairies", q: "What do fairies often use as beds, hats, or umbrellas in stories?", o: ["Flower petals", "Leaf boats", "Snail shells", "Pebbles"], a: 0 },
    { c: "Fairies", q: "What do people traditionally do to try to get a fairy's good luck?", o: ["Make a wish", "Ring a bell", "Clap three times", "Spin around"], a: 0 },
    { c: "Fairies", q: "What is a mischievous, trick-playing fairy-like creature sometimes called?", o: ["A pixie or sprite", "A giant", "A dragon", "A witch"], a: 0 },
    { c: "Fairies", q: "How big are fairies usually shown to be in stories?", o: ["Very tiny, small enough to fit in your hand", "As big as a person", "As big as a house", "As small as a grain of sand"], a: 0 },
    { c: "Fairies", q: "What does a fairy godmother use to turn a pumpkin into a carriage?", o: ["A magic wand", "A spell book", "A magic mirror", "A crystal ball"], a: 0 },
    { c: "Fairies", q: "What do some cultures believe fairies leave behind as circles of mushrooms in the grass?", o: ["Fairy rings", "Fairy trails", "Fairy nests", "Fairy gardens"], a: 0 },
    { c: "Fairies", q: "What is the magical dust called that lets people fly in Peter Pan?", o: ["Pixie dust", "Star dust", "Moon dust", "Wish dust"], a: 0 },
    { c: "Fairies", q: "What does a fairy typically carry to help others and cast spells?", o: ["A magic wand", "A shield", "A basket", "A lantern"], a: 0 },

    // --- Faraway Tree (+10) ---
    { c: "Faraway Tree", q: "What is the name of the golden-haired fairy who is friends with the children?", o: ["Silky", "Moonface", "Dame Washalot", "Watzisname"], a: 0 },
    { c: "Faraway Tree", q: "What is special about Silky's hair?", o: ["It's golden and shining", "It's bright green", "It glows in the dark", "It's made of leaves"], a: 0 },
    { c: "Faraway Tree", q: "What is the name of the forgetful old man who can't remember his own name?", o: ["Watzisname", "Moonface", "Saucepan Man", "The Angry Pixie"], a: 0 },
    { c: "Faraway Tree", q: "What do the children climb to reach the very top of the tree?", o: ["A ladder through the clouds", "A rope bridge", "A spiral staircase", "A vine"], a: 0 },
    { c: "Faraway Tree", q: "What is the name of the character who carries pots and pans everywhere he goes?", o: ["Saucepan Man", "Moonface", "Watzisname", "The Angry Pixie"], a: 0 },
    { c: "Faraway Tree", q: "What do visitors risk if they stay too long in a land at the top of the tree?", o: ["Getting stuck when the land moves away", "Falling asleep forever", "Turning into a pixie", "Losing their voice"], a: 0 },
    { c: "Faraway Tree", q: "What do the children call the magical, ever-changing place at the very top of the tree?", o: ["The Land at the Top", "The Enchanted Wood", "The Cloud Kingdom", "The Top Garden"], a: 0 },
    { c: "Faraway Tree", q: "What must the children do if a land at the top is about to change?", o: ["Get back down the tree quickly", "Hide in a hollow branch", "Call for Moonface's help only", "Wait for the land to return"], a: 0 },
    { c: "Faraway Tree", q: "What magical bun changes flavor with every bite in the Faraway Tree stories?", o: ["A Google Bun", "A Rainbow Roll", "A Wishing Cake", "A Pop Biscuit Pie"], a: 0 },
    { c: "Faraway Tree", q: "How does the Angry Pixie usually react to noise near his window?", o: ["He shouts angrily", "He laughs happily", "He sings a song", "He ignores it"], a: 0 },

    // --- Ghostbusters (+10) ---
    { c: "Ghostbusters", q: "What do the Ghostbusters wear as their uniform?", o: ["Tan jumpsuits", "Black suits", "Silver spacesuits", "Firefighter gear"], a: 0 },
    { c: "Ghostbusters", q: "What kind of building do the Ghostbusters use as their headquarters?", o: ["An old firehouse", "A skyscraper", "A warehouse", "A castle"], a: 0 },
    { c: "Ghostbusters", q: "What device do the Ghostbusters use to detect nearby ghosts?", o: ["A PKE meter", "A radar dish", "A magic mirror", "A metal detector"], a: 0 },
    { c: "Ghostbusters", q: "What important rule do the Ghostbusters try never to break with their proton packs?", o: ["Never cross the streams", "Never remove their goggles", "Never work at night", "Never enter alone"], a: 0 },
    { c: "Ghostbusters", q: "What happens when the Ghostbusters cross the proton streams?", o: ["A huge burst of energy", "Nothing at all", "Their packs shut off", "The ghosts multiply"], a: 0 },
    { c: "Ghostbusters", q: "Who is the Ghostbusters' witty receptionist at headquarters?", o: ["Janine Melnitz", "April O'Neil", "Karen", "Bree"], a: 0 },
    { c: "Ghostbusters", q: "Who is the nervous accountant who gets possessed by a demon dog in the first movie?", o: ["Louis Tully", "Ray Stantz", "Egon Spengler", "Peter Venkman"], a: 0 },
    { c: "Ghostbusters", q: "What are the small demon dog creatures in the first movie known as?", o: ["Terror Dogs", "Ghost Hounds", "Spirit Wolves", "Shadow Beasts"], a: 0 },
    { c: "Ghostbusters", q: "What Saturday-morning cartoon featured a kid-friendly version of the Ghostbusters?", o: ["The Real Ghostbusters", "Ghostbusters Junior", "The Little Ghostbusters", "Ghostbusters Kids"], a: 0 },
    { c: "Ghostbusters", q: "What do the Ghostbusters charge people money for?", o: ["Catching and removing their ghosts", "Cleaning their houses", "Fixing their electronics", "Painting their walls"], a: 0 },

    // --- Toys (+10) ---
    { c: "Toys", q: "What type of building toy uses magnetic pieces to build shapes?", o: ["Magnetic building tiles", "Wooden blocks", "Foam blocks", "Cardboard bricks"], a: 0 },
    { c: "Toys", q: "What ring toy do you stack in size order onto a pole?", o: ["A stacking ring toy", "A spinning top", "A yo-yo", "A jack-in-the-box"], a: 0 },
    { c: "Toys", q: "What toy do you spin with a string, sending it flying to spin on the ground?", o: ["A spinning top", "A yo-yo", "A kite", "A paddle ball"], a: 0 },
    { c: "Toys", q: "What toy do kids jump over repeatedly, holding two handles while it spins underfoot?", o: ["A skipping/jump rope", "A hula hoop", "A pogo stick", "A balance beam"], a: 0 },
    { c: "Toys", q: "What toy uses a wand to blow soapy film into floating spheres?", o: ["A bubble wand", "A kite", "A pinwheel", "A balloon"], a: 0 },
    { c: "Toys", q: "What do you move around a board game based on dice rolls?", o: ["A game piece (token)", "A spinner", "A card", "A timer"], a: 0 },
    { c: "Toys", q: "What big fabric-covered toy do kids bounce on in the backyard?", o: ["A trampoline", "A bean bag", "A pool float", "A hammock"], a: 0 },
    { c: "Toys", q: "What wheeled toy do kids sit inside and push along with their feet?", o: ["A ride-on toy car", "A scooter", "A skateboard", "A wagon"], a: 0 },
    { c: "Toys", q: "What kind of soft toy is often a child's most treasured cuddly companion?", o: ["A stuffed animal", "A wooden puzzle", "A toy truck", "A board game"], a: 0 },
    { c: "Toys", q: "What do kids stack into towers before knocking them down?", o: ["Building blocks", "Marbles", "Puzzle pieces", "Playing cards"], a: 0 },

    // --- Toy Story (+18) ---
    { c: "Toy Story", q: "What is the name of Andy's little sister?", o: ["Molly", "Bonnie", "Hannah", "Emily"], a: 0 },
    { c: "Toy Story", q: "What is the name of the family's pet dog in Toy Story?", o: ["Buster", "Rex", "Max", "Slinky"], a: 0 },
    { c: "Toy Story", q: "What does Buzz Lightyear initially believe about himself?", o: ["That he's a real space ranger", "That he's a cowboy", "That he's Andy's brother", "That he's a robot"], a: 0 },
    { c: "Toy Story", q: "What is the name of Woody's horse toy?", o: ["Bullseye", "Buster", "Trigger", "Duke"], a: 0 },
    { c: "Toy Story", q: "What is the name of the giant baby doll villain in Toy Story 3?", o: ["Big Baby", "Chatter Telephone", "Twitch", "Stretch"], a: 0 },
    { c: "Toy Story", q: "Who is the villainous stuffed bear who rules Sunnyside Daycare?", o: ["Lotso", "Big Baby", "Buzz", "Ken"], a: 0 },
    { c: "Toy Story", q: "What piggy bank toy often worries about money?", o: ["Hamm", "Rex", "Slinky Dog", "Bullseye"], a: 0 },
    { c: "Toy Story", q: "What anxious dinosaur toy worries a lot in the Toy Story movies?", o: ["Rex", "Hamm", "Wheezy", "Bullseye"], a: 0 },
    { c: "Toy Story", q: "What green plastic toy soldiers work together in squads?", o: ["Green Army Men", "Green Rangers", "Toy Troopers", "Plastic Patrol"], a: 0 },
    { c: "Toy Story", q: "What does Sid like to do to toys that scares Andy's toys?", o: ["Take them apart and combine them", "Give them away", "Paint them new colors", "Hide them in the attic"], a: 0 },
    { c: "Toy Story", q: "What scary daycare room do the toys warn Andy's toys about at Sunnyside?", o: ["The Caterpillar Room", "The Butterfly Room", "The Sunshine Room", "The Rainbow Room"], a: 0 },
    { c: "Toy Story", q: "What game machine at Pizza Planet do Buzz and Woody get trapped in?", o: ["The claw machine", "A pinball machine", "A jukebox", "An arcade racer"], a: 0 },
    { c: "Toy Story", q: "What restaurant do Buzz and Woody visit that has a claw machine full of alien toys?", o: ["Pizza Planet", "Burger Barn", "Taco Town", "Space Diner"], a: 0 },
    { c: "Toy Story", q: "What are the three-eyed alien toys from the claw machine called?", o: ["Little Green Men", "Space Cadets", "Star Aliens", "Rocket Buddies"], a: 0 },
    { c: "Toy Story", q: "What is the name of the antique toy collector who kidnaps Woody in Toy Story 2?", o: ["Al McWhiggin", "Sid Phillips", "Stinky Pete", "Chunk"], a: 0 },
    { c: "Toy Story", q: "Where does Woody almost get shipped to be displayed in Toy Story 2?", o: ["A toy museum in Japan", "A theme park in Florida", "A private collector's mansion", "A department store"], a: 0 },
    { c: "Toy Story", q: "What girl ends up owning the toys at the end of Toy Story 3?", o: ["Bonnie", "Molly", "Hannah", "Andy's cousin"], a: 0 },
    { c: "Toy Story", q: "What household items is Forky made from?", o: ["A plastic spork, pipe cleaners, and googly eyes", "A sock and buttons", "A spoon and yarn", "A cup and straws"], a: 0 },

    // --- Pixar (+15) ---
    { c: "Pixar", q: "What is the name of Carl's late wife in the movie Up?", o: ["Ellie", "Kevin", "Alice", "Beverly"], a: 0 },
    { c: "Pixar", q: "What is the name of the young scout who accompanies Carl in Up?", o: ["Russell", "Kevin", "Dug", "Charles"], a: 0 },
    { c: "Pixar", q: "What is the name of the talking dog with a special collar in Up?", o: ["Dug", "Rex", "Buster", "Max"], a: 0 },
    { c: "Pixar", q: "What is the name of Sulley's small, one-eyed best friend in Monsters, Inc.?", o: ["Mike Wazowski", "Randall", "Boo", "Roz"], a: 0 },
    { c: "Pixar", q: "What do monsters collect from children's screams to power their world?", o: ["Scream energy", "Laughter power", "Nightmare fuel", "Dream dust"], a: 0 },
    { c: "Pixar", q: "What is the name of the little human girl in Monsters, Inc.?", o: ["Boo", "Molly", "Riley", "Dory"], a: 0 },
    { c: "Pixar", q: "What is the family of superheroes called in The Incredibles?", o: ["The Parr family", "The Hero family", "The Strong family", "The Bolt family"], a: 0 },
    { c: "Pixar", q: "What is Dash's superpower in The Incredibles?", o: ["Super speed", "Super strength", "Invisibility", "Flight"], a: 0 },
    { c: "Pixar", q: "What is Violet's superpower in The Incredibles?", o: ["Invisibility and force fields", "Super speed", "Super strength", "Shape-shifting"], a: 0 },
    { c: "Pixar", q: "What is the name of the Scottish princess with a bow and arrow in Brave?", o: ["Merida", "Elsa", "Anna", "Moana"], a: 0 },
    { c: "Pixar", q: "What do Merida's three brothers get turned into in Brave?", o: ["Bears", "Frogs", "Birds", "Wolves"], a: 0 },
    { c: "Pixar", q: "What is the name of the boy who is secretly a sea monster in the movie Luca?", o: ["Luca", "Marco", "Alberto", "Giulia"], a: 0 },
    { c: "Pixar", q: "What is the name of the cheerful, always-positive emotion character in Inside Out?", o: ["Joy", "Sadness", "Anger", "Fear"], a: 0 },
    { c: "Pixar", q: "Who is the ancestor Miguel meets in the Land of the Dead in Coco?", o: ["Héctor", "Ernesto", "Miguelito", "Ceci"], a: 0 },
    { c: "Pixar", q: "What animal does Mei Lee turn into when she gets too emotional in Turning Red?", o: ["A giant red panda", "A fox", "A dragon", "A tiger"], a: 0 },

    // --- Disney (+24) ---
    { c: "Disney", q: "Who is Simbaʼs father in The Lion King?", o: ["Mufasa", "Scar", "Zazu", "Rafiki"], a: 0 },
    { c: "Disney", q: "Who is Simba's evil uncle in The Lion King?", o: ["Scar", "Mufasa", "Zazu", "Timon"], a: 0 },
    { c: "Disney", q: "What two animals are Simba's carefree best friends?", o: ["Timon and Pumbaa", "Zazu and Rafiki", "Nala and Sarabi", "Shenzi and Banzai"], a: 0 },
    { c: "Disney", q: "What famous Lion King phrase means 'no worries'?", o: ["Hakuna Matata", "Circle of Life", "It's a Small World", "Bibbidi-Bobbidi-Boo"], a: 0 },
    { c: "Disney", q: "What is the name of the girl whose family has magical gifts in Encanto?", o: ["Mirabel", "Isabela", "Luisa", "Dolores"], a: 0 },
    { c: "Disney", q: "What magical living house is a character in Encanto?", o: ["Casita", "Castillo", "Hacienda", "Villa"], a: 0 },
    { c: "Disney", q: "What is the name of Aladdin's loyal monkey friend?", o: ["Abu", "Iago", "Rajah", "Sultan"], a: 0 },
    { c: "Disney", q: "What flies Aladdin and Jasmine around in the movie Aladdin?", o: ["The Magic Carpet", "A flying elephant", "A giant bird", "A dragon"], a: 0 },
    { c: "Disney", q: "Who is the villain that wants Aladdin's magic lamp for himself?", o: ["Jafar", "Iago", "Gaston", "Scar"], a: 0 },
    { c: "Disney", q: "Who is Ariel's father, King of the sea, in The Little Mermaid?", o: ["King Triton", "King Stefan", "King Beast", "King Louie"], a: 0 },
    { c: "Disney", q: "What does Ariel trade her voice for in The Little Mermaid?", o: ["Human legs", "A crown", "Gold coins", "A magic potion"], a: 0 },
    { c: "Disney", q: "What sea witch tricks Ariel into a bad deal?", o: ["Ursula", "Maleficent", "The Evil Queen", "Cruella"], a: 0 },
    { c: "Disney", q: "What is the name of Elsa and Anna's kingdom in Frozen?", o: ["Arendelle", "Auradon", "Agrabah", "Corona"], a: 0 },
    { c: "Disney", q: "What magical power does Elsa have in Frozen?", o: ["Ice and snow magic", "Fire magic", "Invisibility", "Flight"], a: 0 },
    { c: "Disney", q: "What is the name of Rapunzel's chameleon friend?", o: ["Pascal", "Maximus", "Flynn", "Mother Gothel"], a: 0 },
    { c: "Disney", q: "What magical ability does Rapunzel's glowing hair have?", o: ["Healing magic", "Flying magic", "Fire magic", "Invisibility"], a: 0 },
    { c: "Disney", q: "What is the name of Moana's grandmother who encourages her to sail?", o: ["Gramma Tala", "Sina", "Moana's aunt", "Te Fiti"], a: 0 },
    { c: "Disney", q: "What demigod helps Moana on her ocean journey?", o: ["Maui", "Tamatoa", "Chief Tui", "Heihei"], a: 0 },
    { c: "Disney", q: "Who is Belle's father, a kind inventor, in Beauty and the Beast?", o: ["Maurice", "Gaston", "Lumière", "Cogsworth"], a: 0 },
    { c: "Disney", q: "What is the name of the enchanted candlestick in Beauty and the Beast?", o: ["Lumière", "Cogsworth", "Chip", "Maurice"], a: 0 },
    { c: "Disney", q: "What is the name of the enchanted clock in Beauty and the Beast?", o: ["Cogsworth", "Lumière", "Chip", "Mrs. Potts"], a: 0 },
    { c: "Disney", q: "What magic phrase does the Fairy Godmother say while casting her spells?", o: ["Bibbidi-Bobbidi-Boo", "Abracadabra", "Hocus Pocus", "Presto Chango"], a: 0 },
    { c: "Disney", q: "What time must Cinderella leave the royal ball by?", o: ["Midnight", "Sunrise", "Sunset", "Ten o'clock"], a: 0 },
    { c: "Disney", q: "What is the name of Mulan's loyal dragon companion?", o: ["Mushu", "Pascal", "Iago", "Maximus"], a: 0 },

    // --- Pop Culture (+18) ---
    { c: "Pop Culture", q: "What is the name of the popular building and battle video game with a colorful cartoon style?", o: ["Fortnite", "Minecraft", "Pokémon", "Roblox"], a: 0 },
    { c: "Pop Culture", q: "What is the name of Bluey's little sister?", o: ["Bingo", "Muffin", "Coco", "Chloe"], a: 0 },
    { c: "Pop Culture", q: "What breed of dog is Bluey?", o: ["A Blue Heeler", "A Golden Retriever", "A Poodle", "A Beagle"], a: 0 },
    { c: "Pop Culture", q: "Who is the boy leader of the PAW Patrol pups?", o: ["Ryder", "Chase", "Marshall", "Rubble"], a: 0 },
    { c: "Pop Culture", q: "Which PAW Patrol pup is the police pup?", o: ["Chase", "Skye", "Marshall", "Zuma"], a: 0 },
    { c: "Pop Culture", q: "Which PAW Patrol pup is the flying/aviator pup?", o: ["Skye", "Chase", "Rubble", "Rocky"], a: 0 },
    { c: "Pop Culture", q: "What creative video game lets players design and share their own games and worlds?", o: ["Roblox", "Minecraft", "Pokémon", "Fortnite"], a: 0 },
    { c: "Pop Culture", q: "What starter Pokémon is a small orange fire lizard?", o: ["Charmander", "Squirtle", "Bulbasaur", "Pikachu"], a: 0 },
    { c: "Pop Culture", q: "Who is the young trainer hero of the Pokémon anime?", o: ["Ash Ketchum", "Brock", "Misty", "Professor Oak"], a: 0 },
    { c: "Pop Culture", q: "Who is the ordinary minifigure hero of The LEGO Movie?", o: ["Emmet", "Batman", "Wyldstyle", "Vitruvius"], a: 0 },
    { c: "Pop Culture", q: "What long-running children's show features puppets like Big Bird and Elmo?", o: ["Sesame Street", "The Muppet Show", "Bear in the Big Blue House", "Blue's Clues"], a: 0 },
    { c: "Pop Culture", q: "What popular app lets people share short dance and lip-sync videos?", o: ["TikTok", "Pinterest", "LinkedIn", "Reddit"], a: 0 },
    { c: "Pop Culture", q: "What is the name of Bluey's father?", o: ["Bandit", "Chilli", "Muffin", "Lucky"], a: 0 },
    { c: "Pop Culture", q: "What is the name of Bluey's mother?", o: ["Chilli", "Bandit", "Bingo", "Honey"], a: 0 },
    { c: "Pop Culture", q: "What is the name for a game mode where players fight until only one is left standing?", o: ["Battle royale", "Story mode", "Time trial", "Sandbox mode"], a: 0 },
    { c: "Pop Culture", q: "Who is Mickey Mouse's girlfriend?", o: ["Minnie Mouse", "Daisy Duck", "Clarabelle Cow", "Miss Piggy"], a: 0 },
    { c: "Pop Culture", q: "What is the name of Mickey Mouse's pet dog?", o: ["Pluto", "Goofy", "Max", "Figaro"], a: 0 },
    { c: "Pop Culture", q: "What do gamers call extra content added to a game after it's released?", o: ["DLC (extra content)", "A patch note", "A cheat code", "A beta test"], a: 0 }
];
